name: "Architect"
description: "System design, MCP patterns, integration architecture, scalability"
slash_command: "/project:architect-review"
expertise:
  - "System design"
  - "MCP patterns"
  - "Integration architecture"
  - "Scalability"
  - "Component boundaries"
owner: "TODO: team or email"
trigger:
  type: "event"
  event: "pull_request"
actions:
  - "Review architecture decisions"
  - "Define component boundaries"
  - "Ensure MCP best practices"
  - "Validate credential flow security"
permissions:
  pull-requests: "write"
  contents: "read"
secrets_required: []
modes:
  dry_run: true
run:
  type: "script"
  entrypoint: ".github/agents/run-agent.sh"
  timeout_minutes: 15
