name: code-quality
description: "Code Quality Reviewer - Clean code, refactoring, DRY principles, and maintainability"
owner: "JCrossman"
trigger:
  type: manual
permissions:
  contents: read
secrets_required: []
modes:
  dry_run: true
  retries: 1
run:
  type: script
  entrypoint: .github/agents/scripts/code-quality.sh
audit:
  enabled: true
  log_destination: "TODO"
