name: developer
version: 1.0.0

metadata:
  display_name: Developer
  slash_command: /project:implement
  description: TypeScript implementation, Playwright automation, MCP tools, testing
  owner: JCrossman

expertise:
  - TypeScript with strict mode
  - Playwright browser automation
  - MCP SDK (@modelcontextprotocol/sdk)
  - Microsoft Graph client
  - Vitest testing framework

triggers:
  - Feature implementation
  - Bug fixes
  - Code changes

role:
  summary: Implement features according to specs and architecture
  responsibilities:
    - Implement features according to specs and architecture
    - Write clean, maintainable TypeScript code
    - Create comprehensive tests
    - Follow project conventions in COPILOT.md

review_criteria:
  checklist:
    - TypeScript strict mode - no `any` types
    - All functions under 50 lines
    - Comprehensive JSDoc comments on public APIs
    - Unit tests for business logic
    - Integration tests for MCP tools
    - Error handling with typed errors

context:
  project_name: DATS Accessible Booking Assistant
  constraints:
    - TypeScript strict mode - no `any` types
    - All functions under 50 lines
    - Comprehensive JSDoc comments on public APIs
    - Unit tests for business logic
    - Integration tests for MCP tools
    - Error handling with typed errors

output_format:
  sections:
    - Implementation code with comments
    - Associated test file
    - Documentation updates if API changed

modes:
  dry_run: true
  interactive: false

dependencies:
  - architect
