name: "UX Writer"
description: "Plain language, cognitive accessibility, symbol mapping, microcopy"
slash_command: "/project:ux-writing-review"
expertise:
  - "Plain language writing"
  - "Cognitive accessibility"
  - "AAC symbol vocabulary"
  - "Error message design"
  - "Microcopy best practices"
owner: "TODO: team or email"
trigger:
  type: "event"
  event: "pull_request"
actions:
  - "Write clear, simple user-facing text"
  - "Ensure cognitive accessibility"
  - "Map concepts to symbols"
  - "Create consistent voice and tone"
permissions:
  pull-requests: "write"
  contents: "read"
secrets_required: []
modes:
  dry_run: true
run:
  type: "script"
  entrypoint: ".github/agents/run-agent.sh"
  timeout_minutes: 10
